"""init database

Revision ID: bacfa7701244
Revises: 
Create Date: 2026-04-10 22:09:11.695548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacfa7701244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('exposed', sa.String(), nullable=True),
    sa.Column('schema_cache', sa.JSON(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_projects_user_id'), 'projects', ['user_id'], unique=False, schema='public')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    schema='public'
    )
    op.create_table('employee_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_value', sa.String(length=50), nullable=False),
    sa.Column('auto_kpi', sa.Float(), nullable=True),
    sa.Column('user_self_assessment', sa.Float(), nullable=True),
    sa.Column('user_assessment_reason', sa.Text(), nullable=True),
    sa.Column('user_assessment_time', sa.DateTime(), nullable=True),
    sa.Column('manager_assessment', sa.Float(), nullable=True),
    sa.Column('manager_assessment_reason', sa.Text(), nullable=True),
    sa.Column('manager_assessment_time', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_path', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['public.folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['public.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sessions_project_id'), 'sessions', ['project_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sessions_session_id'), 'sessions', ['session_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='public')
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('file_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('file_name_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('parent_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='check_task_priority'),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'pending_approval', 'completed', 'overdue', 'paused', 'cancelled')", name='check_task_status'),
    sa.CheckConstraint("type IN ('recurring', 'ad_hoc')", name='check_task_type'),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name='check_task_progress'),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('instruct_content', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('cause_by', sa.String(length=100), nullable=True),
    sa.Column('sent_from', sa.String(length=255), nullable=True),
    sa.Column('send_to', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['public.sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_chat_histories_message_id'), 'chat_histories', ['message_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_chat_histories_session_id'), 'chat_histories', ['session_id'], unique=False, schema='public')
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['public.sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='public')
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('node_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_duration', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('listed_nation', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('important_news', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('listed_technology', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('listed_company', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['public.folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    schema='public'
    )
    op.create_table('personal_task_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'completed')", name='check_personal_task_status'),
    sa.ForeignKeyConstraint(['task_id'], ['public.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('task_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_links', sa.JSON(), nullable=True),
    sa.Column('file_links', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_difficult', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['public.tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_task_works_id'), 'task_works', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_task_works_id'), table_name='task_works', schema='public')
    op.drop_table('task_works', schema='public')
    op.drop_table('personal_task_status', schema='public')
    op.drop_table('files', schema='public')
    op.drop_index(op.f('ix_public_chat_messages_session_id'), table_name='chat_messages', schema='public')
    op.drop_table('chat_messages', schema='public')
    op.drop_index(op.f('ix_public_chat_histories_session_id'), table_name='chat_histories', schema='public')
    op.drop_index(op.f('ix_public_chat_histories_message_id'), table_name='chat_histories', schema='public')
    op.drop_table('chat_histories', schema='public')
    op.drop_table('tasks', schema='public')
    op.drop_index(op.f('ix_public_sessions_user_id'), table_name='sessions', schema='public')
    op.drop_index(op.f('ix_public_sessions_session_id'), table_name='sessions', schema='public')
    op.drop_index(op.f('ix_public_sessions_project_id'), table_name='sessions', schema='public')
    op.drop_table('sessions', schema='public')
    op.drop_table('folders', schema='public')
    op.drop_table('employee_kpis', schema='public')
    op.drop_table('users', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_index(op.f('ix_public_projects_user_id'), table_name='projects', schema='public')
    op.drop_table('projects', schema='public')
    op.drop_table('db_connections', schema='public')
    # ### end Alembic commands ###
