"""remove tables

Revision ID: 9c4cc7df20b6
Revises: 0fbef91a3ee5
Create Date: 2026-04-18 14:50:14.875537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c4cc7df20b6'
down_revision: Union[str, None] = '0fbef91a3ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_kpis')
    op.drop_table('personal_task_status')
    op.drop_index(op.f('ix_public_task_works_id'), table_name='task_works')
    op.drop_table('task_works')
    op.drop_table('tasks')
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('edges_file_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_target_node_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_source_node_id_fkey'), 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['target_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'edges', 'nodes', ['source_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('nodes_file_id_fkey'), 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('roles_parent_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('roles_parent_id_fkey'), 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'nodes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('nodes_file_id_fkey'), 'nodes', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('edges_source_node_id_fkey'), 'edges', 'nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_target_node_id_fkey'), 'edges', 'nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_file_id_fkey'), 'edges', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    op.create_table('task_works',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('file_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_difficult', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('task_works_created_by_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_works_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_works_pkey'))
    )
    op.create_index(op.f('ix_public_task_works_id'), 'task_works', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tasks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('file_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('file_name_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('parent_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority::text = ANY (ARRAY['low'::character varying::text, 'medium'::character varying::text, 'high'::character varying::text, 'critical'::character varying::text])", name='check_task_priority'),
    sa.CheckConstraint("status::text = ANY (ARRAY['new'::character varying::text, 'in_progress'::character varying::text, 'pending_approval'::character varying::text, 'completed'::character varying::text, 'overdue'::character varying::text, 'paused'::character varying::text, 'cancelled'::character varying::text])", name='check_task_status'),
    sa.CheckConstraint("type::text = ANY (ARRAY['recurring'::character varying::text, 'ad_hoc'::character varying::text])", name='check_task_type'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='check_task_progress'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tasks_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('personal_task_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['new'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text])", name=op.f('check_personal_task_status')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('personal_task_status_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('personal_task_status_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_task_status_pkey'))
    )
    op.create_table('employee_kpis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auto_kpi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_self_assessment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_assessment_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_assessment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('manager_assessment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manager_assessment_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_assessment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assessed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('employee_kpis_assessed_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('employee_kpis_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_kpis_pkey'))
    )
    # ### end Alembic commands ###
