"""add server default for topic_classify_retries

Revision ID: 5beabd6d2c20
Revises: 9012808b9d57
Create Date: 2026-04-24 20:50:19.223202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5beabd6d2c20'
down_revision: Union[str, None] = '9012808b9d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', name='frequencyenum', native_enum=False, length=20), nullable=False),
    sa.Column('creation_day', sa.Enum('today', 'tomorrow', name='creationdayenum', native_enum=False, length=20), nullable=True),
    sa.Column('creation_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_indefinite', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('compiling', 'completed', 'failed', name='reportstatusenum', native_enum=False, length=20), server_default='compiling', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['public.report_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('report_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queuing', 'processing', 'completed', 'error', name='reportdocumentstatus', native_enum=False, length=20), server_default='queuing', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['public.files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['public.reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('edges_source_node_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_target_node_id_fkey'), 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['source_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'nodes', ['target_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('file_topics_topic_id_fkey'), 'file_topics', type_='foreignkey')
    op.drop_constraint(op.f('file_topics_file_id_fkey'), 'file_topics', type_='foreignkey')
    op.create_foreign_key(None, 'file_topics', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_topics', 'topics', ['topic_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('roles_parent_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('topics_created_by_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('topics_created_by_fkey'), 'topics', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('roles_parent_id_fkey'), 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_topics_file_id_fkey'), 'file_topics', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('file_topics_topic_id_fkey'), 'file_topics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('edges_target_node_id_fkey'), 'edges', 'nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_source_node_id_fkey'), 'edges', 'nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    op.drop_table('report_documents', schema='public')
    op.drop_table('reports', schema='public')
    op.drop_table('report_templates', schema='public')
    # ### end Alembic commands ###
