"""add extraction status and remove file_id from nodes edges

Revision ID: 2cc76c84735b
Revises: 9c4cc7df20b6
Create Date: 2026-04-23 03:10:40.045545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc76c84735b'
down_revision: Union[str, None] = '9c4cc7df20b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_public_edges_file_id'), table_name='edges')
    op.drop_constraint(op.f('edges_source_node_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_file_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_target_node_id_fkey'), 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['source_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'nodes', ['target_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('edges', 'file_id')
    op.add_column('files', sa.Column('extraction_state', sa.Enum('pending', 'processing', 'failed', 'done', name='extractionstate', native_enum=False, length=20), server_default='pending', nullable=False))
    op.add_column('files', sa.Column('extraction_attempts', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_column('files', 'is_graph_extracted')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_public_nodes_file_id'), table_name='nodes')
    op.drop_constraint(op.f('nodes_file_id_fkey'), 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'file_id')
    op.drop_constraint(op.f('roles_parent_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('roles_parent_id_fkey'), 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('nodes', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('nodes_file_id_fkey'), 'nodes', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_public_nodes_file_id'), 'nodes', ['file_id'], unique=False)
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('files', sa.Column('is_graph_extracted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.drop_column('files', 'extraction_attempts')
    op.drop_column('files', 'extraction_state')
    op.add_column('edges', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('edges_target_node_id_fkey'), 'edges', 'nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_file_id_fkey'), 'edges', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('edges_source_node_id_fkey'), 'edges', 'nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_edges_file_id'), 'edges', ['file_id'], unique=False)
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###
