"""add chat type, connection id for chat_messages table

Revision ID: f4fe1564854a
Revises: 35579ea23454
Create Date: 2026-04-26 10:33:05.367606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fe1564854a'
down_revision: Union[str, None] = '35579ea23454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.add_column('chat_messages', sa.Column('chat_type', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('connection_id', sa.Text(), nullable=True))
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('edges_target_node_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_source_node_id_fkey'), 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['source_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'nodes', ['target_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('file_topics_file_id_fkey'), 'file_topics', type_='foreignkey')
    op.drop_constraint(op.f('file_topics_topic_id_fkey'), 'file_topics', type_='foreignkey')
    op.create_foreign_key(None, 'file_topics', 'topics', ['topic_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_topics', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('report_documents_document_id_fkey'), 'report_documents', type_='foreignkey')
    op.drop_constraint(op.f('report_documents_user_id_fkey'), 'report_documents', type_='foreignkey')
    op.drop_constraint(op.f('report_documents_report_id_fkey'), 'report_documents', type_='foreignkey')
    op.create_foreign_key(None, 'report_documents', 'reports', ['report_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'report_documents', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'report_documents', 'files', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('report_templates_created_by_fkey'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(None, 'report_templates', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('reports_created_by_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_template_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'report_templates', ['template_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('roles_parent_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('topics_created_by_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('topics_created_by_fkey'), 'topics', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('roles_parent_id_fkey'), 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'reports', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reports', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('reports_template_id_fkey'), 'reports', 'report_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('reports_created_by_fkey'), 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'report_templates', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('report_templates_created_by_fkey'), 'report_templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('report_documents_report_id_fkey'), 'report_documents', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('report_documents_user_id_fkey'), 'report_documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('report_documents_document_id_fkey'), 'report_documents', 'files', ['document_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_topics_topic_id_fkey'), 'file_topics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('file_topics_file_id_fkey'), 'file_topics', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('edges_source_node_id_fkey'), 'edges', 'nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_target_node_id_fkey'), 'edges', 'nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_column('chat_messages', 'connection_id')
    op.drop_column('chat_messages', 'chat_type')
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###
