"""update report_templates fields

Revision ID: 2d9e997eac59
Revises: e42d1afa2b4f
Create Date: 2026-05-10 19:32:11.163521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9e997eac59'
down_revision: Union[str, None] = 'e42d1afa2b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('edges_source_node_id_fkey'), 'edges', type_='foreignkey')
    op.drop_constraint(op.f('edges_target_node_id_fkey'), 'edges', type_='foreignkey')
    op.create_foreign_key(None, 'edges', 'nodes', ['target_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'edges', 'nodes', ['source_node_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('file_topics_topic_id_fkey'), 'file_topics', type_='foreignkey')
    op.drop_constraint(op.f('file_topics_file_id_fkey'), 'file_topics', type_='foreignkey')
    op.create_foreign_key(None, 'file_topics', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_topics', 'topics', ['topic_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('report_documents_user_id_fkey'), 'report_documents', type_='foreignkey')
    op.drop_constraint(op.f('report_documents_document_id_fkey'), 'report_documents', type_='foreignkey')
    op.drop_constraint(op.f('report_documents_report_id_fkey'), 'report_documents', type_='foreignkey')
    op.create_foreign_key(None, 'report_documents', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'report_documents', 'files', ['document_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'report_documents', 'reports', ['report_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('report_templates', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('report_templates_created_by_fkey'), 'report_templates', type_='foreignkey')
    op.create_foreign_key(None, 'report_templates', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('reports_created_by_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_template_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'report_templates', ['template_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('roles_parent_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('shared_store_store_id_fkey'), 'shared_store', type_='foreignkey')
    op.drop_constraint(op.f('shared_store_user_id_fkey'), 'shared_store', type_='foreignkey')
    op.create_foreign_key(None, 'shared_store', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'shared_store', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('store_files_store_id_fkey'), 'store_files', type_='foreignkey')
    op.drop_constraint(op.f('store_files_file_id_fkey'), 'store_files', type_='foreignkey')
    op.create_foreign_key(None, 'store_files', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'store_files', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('stores_created_by_fkey'), 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('topics_created_by_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('topics_created_by_fkey'), 'topics', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'stores', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('stores_created_by_fkey'), 'stores', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'store_files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'store_files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('store_files_file_id_fkey'), 'store_files', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('store_files_store_id_fkey'), 'store_files', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shared_store', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'shared_store', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('shared_store_user_id_fkey'), 'shared_store', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('shared_store_store_id_fkey'), 'shared_store', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'roles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('roles_parent_id_fkey'), 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'reports', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reports', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('reports_template_id_fkey'), 'reports', 'report_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('reports_created_by_fkey'), 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'report_templates', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('report_templates_created_by_fkey'), 'report_templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('report_templates', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'report_documents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('report_documents_report_id_fkey'), 'report_documents', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('report_documents_document_id_fkey'), 'report_documents', 'files', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('report_documents_user_id_fkey'), 'report_documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'file_topics', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_topics_file_id_fkey'), 'file_topics', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('file_topics_topic_id_fkey'), 'file_topics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'edges', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('edges_target_node_id_fkey'), 'edges', 'nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edges_source_node_id_fkey'), 'edges', 'nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###
