"""empty message

Revision ID: 3be3c1da2c51
Revises: a7bbf8be83b3
Create Date: 2025-06-21 11:26:18.536213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be3c1da2c51'
down_revision: Union[str, None] = 'a7bbf8be83b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_works', sa.Column('is_difficult', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_works', 'is_difficult')
    # ### end Alembic commands ###
