"""Add processing fields to files table

Revision ID: 64d643ae0e04
Revises: 89bd59c367d2
Create Date: 2025-08-15 06:44:16.281353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64d643ae0e04'
down_revision: Union[str, None] = '89bd59c367d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_versions')
    op.alter_column('employee_kpis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employee_kpis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_employee_kpis_id'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_period'), table_name='employee_kpis')
    op.drop_index(op.f('ix_employee_kpis_user_id'), table_name='employee_kpis')
    op.add_column('files', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'summary')
    op.drop_column('files', 'content')
    op.drop_column('files', 'is_processed')
    op.create_index(op.f('ix_employee_kpis_user_id'), 'employee_kpis', ['user_id'], unique=False)
    op.create_index(op.f('ix_employee_kpis_period'), 'employee_kpis', ['period_type', 'period_value'], unique=False)
    op.create_index(op.f('ix_employee_kpis_id'), 'employee_kpis', ['id'], unique=False)
    op.alter_column('employee_kpis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('employee_kpis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_table('migration_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('migration_versions_pkey'))
    )
    # ### end Alembic commands ###
