"""add nodes, edges and files.is_graph_extracted

Revision ID: 71b966ca9121
Revises: bacfa7701244
Create Date: 2026-04-10 22:53:22.844980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71b966ca9121'
down_revision: Union[str, None] = 'bacfa7701244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['public.files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_type', name='uq_node_name_type'),
    schema='public'
    )
    op.create_index(op.f('ix_public_nodes_file_id'), 'nodes', ['file_id'], unique=False, schema='public')
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Text(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['public.files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_node_id'], ['public.nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['public.nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_edges_file_id'), 'edges', ['file_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_edges_source_node_id'), 'edges', ['source_node_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_edges_target_node_id'), 'edges', ['target_node_id'], unique=False, schema='public')
    op.drop_constraint(op.f('chat_histories_session_id_fkey'), 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['session_id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('employee_kpis_assessed_by_fkey'), 'employee_kpis', type_='foreignkey')
    op.drop_constraint(op.f('employee_kpis_user_id_fkey'), 'employee_kpis', type_='foreignkey')
    op.create_foreign_key(None, 'employee_kpis', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'employee_kpis', 'users', ['assessed_by'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('files', sa.Column('is_graph_extracted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('files_created_by_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_role_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'files', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('folders_role_id_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_created_by_fkey'), 'folders', type_='foreignkey')
    op.drop_constraint(op.f('folders_parent_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'folders', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('personal_task_status_task_id_fkey'), 'personal_task_status', type_='foreignkey')
    op.drop_constraint(op.f('personal_task_status_user_id_fkey'), 'personal_task_status', type_='foreignkey')
    op.create_foreign_key(None, 'personal_task_status', 'tasks', ['task_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'personal_task_status', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_project_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('task_works_task_id_fkey'), 'task_works', type_='foreignkey')
    op.drop_constraint(op.f('task_works_created_by_fkey'), 'task_works', type_='foreignkey')
    op.create_foreign_key(None, 'task_works', 'tasks', ['task_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'task_works', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'task_works', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'task_works', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('task_works_created_by_fkey'), 'task_works', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('task_works_task_id_fkey'), 'task_works', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_project_id_fkey'), 'sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'personal_task_status', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'personal_task_status', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('personal_task_status_user_id_fkey'), 'personal_task_status', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('personal_task_status_task_id_fkey'), 'personal_task_status', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'folders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('folders_parent_id_fkey'), 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('folders_created_by_fkey'), 'folders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('folders_role_id_fkey'), 'folders', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_role_id_fkey'), 'files', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_created_by_fkey'), 'files', 'users', ['created_by'], ['id'])
    op.drop_column('files', 'is_graph_extracted')
    op.drop_constraint(None, 'employee_kpis', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'employee_kpis', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('employee_kpis_user_id_fkey'), 'employee_kpis', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('employee_kpis_assessed_by_fkey'), 'employee_kpis', 'users', ['assessed_by'], ['id'])
    op.drop_constraint(None, 'chat_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chat_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_histories_session_id_fkey'), 'chat_histories', 'sessions', ['session_id'], ['session_id'])
    op.drop_index(op.f('ix_public_edges_target_node_id'), table_name='edges', schema='public')
    op.drop_index(op.f('ix_public_edges_source_node_id'), table_name='edges', schema='public')
    op.drop_index(op.f('ix_public_edges_file_id'), table_name='edges', schema='public')
    op.drop_table('edges', schema='public')
    op.drop_index(op.f('ix_public_nodes_file_id'), table_name='nodes', schema='public')
    op.drop_table('nodes', schema='public')
    # ### end Alembic commands ###
