"""create_employee_kpi_table

Revision ID: 89bd59c367d2
Revises: 89ead7fb60dc
Create Date: 2025-08-03 09:14:17.365720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bd59c367d2'
down_revision: Union[str, None] = '89ead7fb60dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_value', sa.String(length=50), nullable=False),
    sa.Column('auto_kpi', sa.Float(), nullable=True),
    sa.Column('user_self_assessment', sa.Float(), nullable=True),
    sa.Column('user_assessment_reason', sa.Text(), nullable=True),
    sa.Column('user_assessment_time', sa.DateTime(), nullable=True),
    sa.Column('manager_assessment', sa.Float(), nullable=True),
    sa.Column('manager_assessment_reason', sa.Text(), nullable=True),
    sa.Column('manager_assessment_time', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('personal_task_status', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('personal_task_status', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'new'::character varying"),
               existing_nullable=False)
    op.drop_table('employee_kpis')
    # ### end Alembic commands ###
