"""empty message

Revision ID: e4aa627a63a7
Revises: 
Create Date: 2025-05-27 23:33:54.134706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4aa627a63a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('approval_comments')
    op.drop_table('task_custom_field_values')
    op.drop_table('work_reminders')
    op.drop_table('task_schedule')
    op.drop_table('task_logs')
    op.drop_table('approval_history')
    op.drop_table('work_history')
    op.drop_table('roles')
    op.drop_table('work_comments')
    op.drop_table('custom_fields')
    op.drop_table('task_assignments')
    op.drop_table('work')
    op.drop_table('approval_notifications')
    op.drop_table('approval_flows')
    op.drop_table('approval_attachments')
    op.drop_table('task_files')
    op.drop_table('approval_workflows')
    op.drop_index(op.f('idx_tasks_parent_path'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('approval_requests')
    op.drop_table('users')

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.TEXT(), server_default=sa.text("'submitted'::text"), autoincrement=False, nullable=True),
    sa.Column('final_decision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_requester'),
    sa.PrimaryKeyConstraint('id', name='approval_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'medium'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])", name='tasks_priority_check'),
    sa.CheckConstraint("status = ANY (ARRAY['new'::text, 'in_progress'::text, 'pending_approval'::text, 'completed'::text, 'overdue'::text, 'paused'::text, 'cancelled'::text])", name='tasks_status_check'),
    sa.CheckConstraint("type = ANY (ARRAY['recurring'::text, 'ad_hoc'::text])", name='tasks_type_check'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='tasks_progress_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tasks_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_tasks_parent_path'), 'tasks', ['parent_path'], unique=False)
    op.create_table('approval_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_or_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_role', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_workflows_pkey'))
    )
    op.create_table('task_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_files_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('task_files_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_files_pkey'))
    )
    op.create_table('approval_attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_attach_request')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attach_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_attachments_pkey'))
    )
    op.create_table('approval_flows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'waiting'::text"), autoincrement=False, nullable=True),
    sa.Column('decision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_flow_approver')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_flow_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_flows_pkey'))
    )
    op.create_table('approval_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notify_user')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_notify_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_notifications_pkey'))
    )
    op.create_table('work',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_work_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False),
    sa.Column('important_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_owner'),
    sa.ForeignKeyConstraint(['parent_work_id'], ['work.id'], name='fk_parent_work'),
    sa.PrimaryKeyConstraint('id', name='work_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('responsibility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role = ANY (ARRAY['owner'::text, 'collaborator'::text])", name=op.f('task_assignments_role_check')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('task_assignments_progress_check')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_assignments_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_assignments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_assignments_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("field_type = ANY (ARRAY['text'::text, 'number'::text, 'date'::text, 'enum'::text, 'boolean'::text])", name='custom_fields_field_type_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='custom_fields_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_fields_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('work_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('commenter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name=op.f('fk_work_comment_user')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('fk_work_comment_work')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_comments_pkey'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_roles_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_table('work_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_work_history_actor')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('fk_work_history_work')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_history_pkey'))
    )
    op.create_table('approval_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_history_actor')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_history_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_history_pkey'))
    )
    op.create_table('task_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_logs_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_logs_pkey'))
    )
    op.create_table('task_schedule',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recurrence_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.CheckConstraint("recurrence_type = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'custom'::text])", name=op.f('task_schedule_recurrence_type_check')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_schedule_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_schedule_pkey'))
    )
    op.create_table('work_reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('remind_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('method', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('fk_work_reminder')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_reminders_pkey'))
    )
    op.create_table('task_custom_field_values',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name=op.f('task_custom_field_values_field_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_custom_field_values_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_custom_field_values_pkey'))
    )
    op.create_table('approval_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('commenter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name=op.f('fk_comment_user')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('fk_comment_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_comments_pkey'))
    )
    op.drop_table('homes')
    # ### end Alembic commands ###
