"""remove unnecessary table

Revision ID: ed984f9db906
Revises: 634d9d2868d1
Create Date: 2025-08-22 05:17:30.269142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed984f9db906'
down_revision: Union[str, None] = '634d9d2868d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all unnecessary tables with CASCADE to handle dependencies
    op.execute('DROP TABLE IF EXISTS approval_attachments CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_comments CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_flows CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_history CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_notifications CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_requests CASCADE')
    op.execute('DROP TABLE IF EXISTS approval_workflows CASCADE')
    op.execute('DROP TABLE IF EXISTS custom_fields CASCADE')
    op.execute('DROP TABLE IF EXISTS homes CASCADE')
    op.execute('DROP TABLE IF EXISTS task_assignments CASCADE')
    op.execute('DROP TABLE IF EXISTS task_custom_field_values CASCADE')
    op.execute('DROP TABLE IF EXISTS task_files CASCADE')
    op.execute('DROP TABLE IF EXISTS task_logs CASCADE')
    op.execute('DROP TABLE IF EXISTS task_schedule CASCADE')
    op.execute('DROP TABLE IF EXISTS work CASCADE')
    op.execute('DROP TABLE IF EXISTS work_comments CASCADE')
    op.execute('DROP TABLE IF EXISTS work_history CASCADE')
    op.execute('DROP TABLE IF EXISTS work_reminders CASCADE')
    
    op.alter_column('tasks', 'file_list',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('tasks', 'file_name_list',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'file_name_list',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('tasks', 'file_list',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    
    # Recreate all dropped tables in reverse order
    op.create_table('homes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('altitude', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coordinates', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('homes_pkey'))
    )
    
    op.create_table('work_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remind_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("method::text = ANY (ARRAY['system'::character varying, 'email'::character varying, 'app'::character varying]::text[])", name=op.f('check_reminder_method')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('work_reminders_work_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_reminders_pkey'))
    )
    
    op.create_table('work_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('work_history_actor_id_fkey')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('work_history_work_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_history_pkey'))
    )
    
    op.create_table('work_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commenter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name=op.f('work_comments_commenter_id_fkey')),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], name=op.f('work_comments_work_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_comments_pkey'))
    )
    
    op.create_table('work',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_work_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('important_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['new'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'overdue'::character varying, 'paused'::character varying, 'cancelled'::character varying]::text[])", name=op.f('check_work_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('work_owner_id_fkey')),
    sa.ForeignKeyConstraint(['parent_work_id'], ['work.id'], name=op.f('work_parent_work_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('work_pkey'))
    )
    
    op.create_table('task_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recurrence_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.CheckConstraint("recurrence_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'custom'::character varying]::text[])", name=op.f('check_recurrence_type')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_schedule_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_schedule_pkey'))
    )
    
    op.create_table('task_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_logs_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_logs_pkey'))
    )
    
    op.create_table('task_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_files_task_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('task_files_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_files_pkey'))
    )
    
    op.create_table('custom_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("field_type::text = ANY (ARRAY['text'::character varying, 'number'::character varying, 'date'::character varying, 'enum'::character varying, 'boolean'::character varying]::text[])", name=op.f('check_field_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('custom_fields_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_fields_pkey'))
    )
    
    op.create_table('task_custom_field_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name=op.f('task_custom_field_values_field_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_custom_field_values_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_custom_field_values_pkey'))
    )
    
    op.create_table('task_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('responsibility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("progress >= 0 AND progress <= 100", name=op.f('check_assignment_progress')),
    sa.CheckConstraint("role::text = ANY (ARRAY['owner'::character varying, 'collaborator'::character varying]::text[])", name=op.f('check_assignment_role')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_assignments_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_assignments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_assignments_pkey'))
    )
    
    op.create_table('approval_workflows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_or_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_role', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_or_user_id'], ['users.id'], name=op.f('approval_workflows_role_or_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_workflows_pkey'))
    )
    
    op.create_table('approval_requests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('approval_requests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('final_decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('final_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("current_status::text = ANY (ARRAY['submitted'::character varying, 'received'::character varying, 'processing'::character varying, 'approved'::character varying, 'rejected'::character varying, 'need_revision'::character varying]::text[])", name='check_approval_status'),
    sa.CheckConstraint("final_decision::text = ANY (ARRAY['approved'::character varying, 'rejected'::character varying, 'need_revision'::character varying]::text[])", name='check_final_decision'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='approval_requests_requester_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='approval_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    
    op.create_table('approval_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('approval_notifications_recipient_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_notifications_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_notifications_pkey'))
    )
    
    op.create_table('approval_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('approval_history_actor_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_history_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_history_pkey'))
    )
    
    op.create_table('approval_flows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['waiting'::character varying, 'approved'::character varying, 'rejected'::character varying, 'need_revision'::character varying, 'transferred'::character varying]::text[])", name=op.f('check_flow_status')),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('approval_flows_approver_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_flows_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_flows_pkey'))
    )
    
    op.create_table('approval_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commenter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], name=op.f('approval_comments_commenter_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_comments_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_comments_pkey'))
    )
    
    op.create_table('approval_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_attachments_request_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('approval_attachments_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_attachments_pkey'))
    )
    # ### end Alembic commands ###
